djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('student.urls')),
    path('',include('professor.urls')),
    path('',include('userextend.urls')),
    path('',include('django.contrib.auth.urls')),
    path('',include('achievements.urls')),
    path('',include('ourteam.urls')),
    path('',include('catalog.urls')),
    path('',include('contact.urls')),


]

djangoProject/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('',views.HomeTemplateView.as_view(), name='home')
]

djangoProject/student/models.py
from django.db import models

from professor.models import Professor


class Student(models.Model):
    class Meta:
        unique_together = ("first_name", "last_name")

    gender_choices = (('male','Male'),('female','Female'))

    first_name = models.CharField(max_length=30 )
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    is_olympic = models.BooleanField(default=False)
    email = models.EmailField(max_length=40)
    description = models.TextField(max_length=1000)
    start_date = models.DateTimeField()
    end_date  = models.DateField()
    average = models.FloatField()
    gender = models.CharField(max_length=20, choices=gender_choices)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)

    #campuri auxiliare
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True) # se va salva data si ora cand a fost adaugata inregistrarea
    updated_at = models.DateTimeField(auto_now=True) #se va modifica data si ora cand se vor realiza modificarile pe inregistrare


    def __str__(self):
        return f"{self.first_name}, {self.last_name}"

    @property
    def get_full_name(self):
         return str(self)

djangoProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
</head>
<body>
{% include 'menu.html' %}
{% block content %}
{%  endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
})
</script>
<script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})
</script>
</body>
</html>

djangoProject/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#181e36">
    <div class="container-fluid">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <a class="navbar-brand" href="{% url 'our_achievements' %}">Our achievments</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Students
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if perms.student.add_student %}
                            <li><a class="dropdown-item" href="{% url 'create_student' %}">Create a new student</a>
                            </li>
                        {% endif %}
                        {% if perms.student.view_list_of_students %}
                            <li><a class="dropdown-item" href="{% url 'list_of_students' %}">List of students</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Professors
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if perms.professor.add_professor %}
                                <li><a class="dropdown-item" href="{% url 'create_professor' %}">Create a new
                                    professor</a></li>
                            {% endif %}

                                <li><a class="dropdown-item" href="{% url 'list_of_professors' %}">List of
                                    professors</a></li>

                        </ul>
                    </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Catalog
                    </a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if perms.catalog.can_add_grades %}
                                <li><a class="dropdown-item" href="{% url 'catalog-add-grade' %}">Add new grades</a>
                                </li>
                            {% endif %}

                                <li><a class="dropdown-item" href="{% url 'list_of_grades' %}">List of
                                    grades</a></li>

                        </ul>
                        </li>
                    {% endif %}

            </ul>


            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="btn btn-primary">Logout, {{ request.user.username }}</a>
            {% else %}
                <a href="{% url 'create_user' %}" class="btn btn-secondary">Sign up</a>
                <a href="{% url 'login' %}" class="btn btn-outline-info">Login</a>

            {% endif %}

        </div>
    </div>
</nav>